image:
  repository: selcpcommonacr.azurecr.io/selfcareonboardingbackend
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://imprese.notifichedigitali.it,https://api-pnpg.selfcare.pagopa.it,https://pnpg.selfcare.pagopa.it"
  tls:
    - hosts:
        - prod01.pnpg.internal.selfcare.pagopa.it
      secretName: prod01-pnpg-internal-selfcare-pagopa-it
  hosts:
    - host: "prod01.pnpg.internal.selfcare.pagopa.it"
      paths:
        - path: /imprese/onboarding/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_ONBOARDING_LOG_LEVEL: "INFO"
  REST_CLIENT_LOGGER_LEVEL: "BASIC"
  ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS: "{'prod-pn-pg':{'*'}}"
  MS_ONBOARDING_URL: "selc-p-pnpg-onboardingbackend-ca.redbeach-5da5166f.westeurope.azurecontainerapps.io"
  REST_CLIENT_READ_TIMEOUT: "60000"
  REST_CLIENT_CONNECT_TIMEOUT: "5000"
