image:
  repository: selcucommonacr.azurecr.io/selfcareonboardingbackend
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - uat01.pnpg.internal.uat.selfcare.pagopa.it
      secretName: uat01-pnpg-internal-uat-selfcare-pagopa-it
  hosts:
    - host: "uat01.pnpg.internal.uat.selfcare.pagopa.it"
      paths:
        - path: /onboarding/v1/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_ONBOARDING_LOG_LEVEL: "DEBUG"
  REST_CLIENT_LOGGER_LEVEL: "FULL"