replicaCount: 0

image:
  repository: selcdcommonacr.azurecr.io/selfcareonboardingbackend

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://imprese.dev.notifichedigitali.it,https://pnpg.dev.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - dev01.pnpg.internal.dev.selfcare.pagopa.it
      secretName: dev01-pnpg-internal-dev-selfcare-pagopa-it
  hosts:
    - host: "dev01.pnpg.internal.dev.selfcare.pagopa.it"
      paths:
        - path: /onboarding/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 0
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_ONBOARDING_LOG_LEVEL: "DEBUG"
  REST_CLIENT_LOGGER_LEVEL: "FULL"
  MS_ONBOARDING_URL: "https://selc-d-pnpg-onboarding-ms-ca.whiteglacier-211c4885.westeurope.azurecontainerapps.io"