server:
  port: ${B4F_ONBOARDING_SERVER_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      - swaggerEN

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.selfcare.onboarding: ${B4F_ONBOARDING_LOG_LEVEL:DEBUG}