/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.onboarding.web.model;

import it.pagopa.selfcare.onboarding.connector.model.onboarding.OnboardingResource;
import lombok.Getter;
import lombok.Setter;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.io.File;

@Getter
@Setter
public class OnboardingResponse implements OnboardingResource {

    @NotBlank
    private String token;

    @NotNull
    private File document;

}
