/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.onboarding.connector.model.onboarding;

import it.pagopa.selfcare.onboarding.common.InstitutionType;
import it.pagopa.selfcare.onboarding.connector.model.institutions.Institution;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;
import java.util.Optional;


@Data
@NoArgsConstructor
public class OnboardingData {

    private String id;
    private String institutionExternalId;
    private String taxCode;
    private String subunitCode;
    private String subunitType;
    private String productId;
    private String productName;
    private String status;
    private String istatCode;
    private List<User> users;
    private String contractPath;
    private String contractVersion;
    private Billing billing;
    private InstitutionLocation location;
    private InstitutionUpdate institutionUpdate;
    private InstitutionType institutionType;
    private String origin;
    private String originId;
    private String pricingPlan;
    private String businessName;
    private boolean existsInRegistry;
    private LocalDateTime updatedAt;
    private LocalDateTime expiringDate;
    private String reasonForReject;
    private Boolean isAggregator;
    private List<Institution> aggregates;
    private List<String> attachments;
    private List<String> atecoCodes;
    private Payment payment;
    private Boolean toAddOnAggregates;
    private UserRequester userRequest;
    public List<User> getUsers() {
        return Optional.ofNullable(users).orElse(Collections.emptyList());
    }

}
