/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.onboarding.connector.model.onboarding;

public interface UserInfo {

    String getName();

    String getSurname();

    String getTaxCode();

    PartyRole getRole();

    String getEmail();

    String getProductRole();

    void setProductRole(String productRole); //TODO: verify usefulness

}
