server:
  port: ${B4F_ONBOARDING_SERVER_PORT:8080}

spring:
  application:
    name: "selc-onboarding"
    version: "0.0.1-SNAPSHOT"
  profiles:
    include:
      - swaggerEN

info:
  build:
    artifact: "selc-onboarding"
    name: "selc-onboarding"
    description: "Self Care OnBoarding Backend"
    version: "0.0.1-SNAPSHOT"


logging:
  level:
    it.pagopa.selfcare.dashboard: ${B4F_ONBOARDING_LOG_LEVEL:DEBUG}