image:
  repository: selcdacr.azurecr.io/selfcareonboardingbackend

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.dev.selfcare.pagopa.it
      secretName: selc-internal-dev-selfcare-pagopa-it
  hosts:
    - host: selc.internal.dev.selfcare.pagopa.it
      paths:
        - path: /onboarding/v1/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_ONBOARDING_LOG_LEVEL: "DEBUG"
  REST_CLIENT_LOGGER_LEVEL: "FULL"
  MS_ONBOARDING_URL: "https://selc-onboarding-ms--vu6nz6h.orangecoast-e7702c22.westeurope.azurecontainerapps.io"
  ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS: "{'prod-interop':{'*'},'prod-pn':{'*'},'prod-io':{'*'},'prod-io-premium':{'*'},'prod-pagopa':{'*'},'prod-fd':{'*'},'prod-fd-garantito':{'*'},'prod-io-sign':{'*'}}"