replicaCount: 2

image:
  repository: selcpacr.azurecr.io/selfcareonboardingbackend
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"
  tls:
    - hosts:
        - selc.internal.selfcare.pagopa.it
      secretName: selc-internal-selfcare-pagopa-it
  hosts:
    - host: "selc.internal.selfcare.pagopa.it"
      paths:
        - path: /onboarding/v1/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 1

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_ONBOARDING_LOG_LEVEL: "INFO"
  REST_CLIENT_LOGGER_LEVEL: "BASIC"
  ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS: "{'prod-interop':{'*'},'prod-pn':{'*'},'prod-pagopa':{'*'},'prod-io':{'*'},'prod-io-premium':{'*'},'prod-io-sign':{'*'}}"
  REST_CLIENT_READ_TIMEOUT: "60000"
  REST_CLIENT_CONNECT_TIMEOUT: "60000"
