/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.onboarding.connector.rest.model;

import it.pagopa.selfcare.onboarding.connector.model.onboarding.BillingData;
import it.pagopa.selfcare.onboarding.connector.model.onboarding.OrganizationType;
import it.pagopa.selfcare.onboarding.connector.model.onboarding.User;
import lombok.Data;

import java.util.List;

@Data
public class OnboardingRequest {

    private String institutionId;
    private List<User> users;
    private OnboardingContract contract;
    private BillingData billingData;
    private OrganizationType organizationType;
}
